"""Finite-state community switching as a stationary Markov reward process.

Each community state carries a state-specific log-fitness selection value.  In
this repository those rewards can be produced upstream by finite sensing tasks
through ``structural_selection_state``; the Markov layer then determines how
those selection states are occupied and temporally correlated.

For stationary distribution pi, transition matrix P, and reward vector s,

    mu = sum_i pi_i s_i

and with centered rewards c=s-mu,

    gamma(k) = sum_i pi_i c_i (P^k c)_i.

Hence for S_H=sum_{t=1}^H s(X_t),

    E[S_H]   = H mu
    Var(S_H) = H gamma(0) + 2 sum_{k=1}^{H-1}(H-k) gamma(k).

These are standard stationary Markov-reward identities.  The repository-specific
role is to connect them to selection values generated by exact adaptive/fixed
sensing structure.
"""

from __future__ import annotations

from dataclasses import dataclass
from math import inf, isfinite, sqrt
from typing import Sequence

from .core import FiniteTask
from .structural_eco_evolution import structural_selection_state


_TOL = 1e-10


def _validate(
    stationary: Sequence[float],
    transition: Sequence[Sequence[float]],
    rewards: Sequence[float],
) -> tuple[tuple[float, ...], tuple[tuple[float, ...], ...], tuple[float, ...]]:
    pi = tuple(float(x) for x in stationary)
    P = tuple(tuple(float(x) for x in row) for row in transition)
    s = tuple(float(x) for x in rewards)
    n = len(pi)
    if n == 0:
        raise ValueError("stationary distribution must be non-empty")
    if len(P) != n or any(len(row) != n for row in P):
        raise ValueError("transition matrix must be square and match stationary length")
    if len(s) != n:
        raise ValueError("reward vector must match stationary length")
    if any(not isfinite(x) or x < -_TOL or x > 1.0 + _TOL for x in pi):
        raise ValueError("stationary probabilities must lie in [0,1]")
    if abs(sum(pi) - 1.0) > _TOL:
        raise ValueError("stationary probabilities must sum to one")
    for row in P:
        if any(not isfinite(x) or x < -_TOL or x > 1.0 + _TOL for x in row):
            raise ValueError("transition probabilities must lie in [0,1]")
        if abs(sum(row) - 1.0) > _TOL:
            raise ValueError("every transition row must sum to one")
    if any(not isfinite(x) for x in s):
        raise ValueError("selection rewards must be finite")

    # Verify pi P = pi.  The caller supplies the stationary distribution so that
    # this module does not need a numerical eigensolver dependency.
    for j in range(n):
        incoming = sum(pi[i] * P[i][j] for i in range(n))
        if abs(incoming - pi[j]) > _TOL:
            raise ValueError("supplied stationary distribution is not stationary for transition matrix")
    return pi, P, s


def _matvec(P: tuple[tuple[float, ...], ...], vector: tuple[float, ...]) -> tuple[float, ...]:
    return tuple(sum(P[i][j] * vector[j] for j in range(len(vector))) for i in range(len(P)))


def stationary_mean_selection(
    stationary: Sequence[float],
    transition: Sequence[Sequence[float]],
    rewards: Sequence[float],
) -> float:
    """Long-run mean state-specific selection under stationary community occupancy."""

    pi, _, s = _validate(stationary, transition, rewards)
    return sum(pi[i] * s[i] for i in range(len(pi)))


def stationary_mean_absolute_selection(
    stationary: Sequence[float],
    transition: Sequence[Sequence[float]],
    rewards: Sequence[float],
) -> float:
    """Expected absolute per-generation selection activity in stationarity."""

    pi, _, s = _validate(stationary, transition, rewards)
    return sum(pi[i] * abs(s[i]) for i in range(len(pi)))


def lag_covariance(
    lag: int,
    stationary: Sequence[float],
    transition: Sequence[Sequence[float]],
    rewards: Sequence[float],
) -> float:
    """Stationary covariance Cov(s_t, s_{t+lag})."""

    k = int(lag)
    if k < 0:
        raise ValueError("lag must be non-negative")
    pi, P, s = _validate(stationary, transition, rewards)
    mu = sum(pi[i] * s[i] for i in range(len(pi)))
    centered = tuple(x - mu for x in s)
    future = centered
    for _ in range(k):
        future = _matvec(P, future)
    return sum(pi[i] * centered[i] * future[i] for i in range(len(pi)))


def covariance_sequence(
    max_lag: int,
    stationary: Sequence[float],
    transition: Sequence[Sequence[float]],
    rewards: Sequence[float],
) -> tuple[float, ...]:
    """Return gamma(0)..gamma(max_lag)."""

    K = int(max_lag)
    if K < 0:
        raise ValueError("max_lag must be non-negative")
    pi, P, s = _validate(stationary, transition, rewards)
    mu = sum(pi[i] * s[i] for i in range(len(pi)))
    centered = tuple(x - mu for x in s)
    future = centered
    out = []
    for _ in range(K + 1):
        out.append(sum(pi[i] * centered[i] * future[i] for i in range(len(pi))))
        future = _matvec(P, future)
    return tuple(out)


def expected_cumulative_selection(
    horizon: int,
    stationary: Sequence[float],
    transition: Sequence[Sequence[float]],
    rewards: Sequence[float],
) -> float:
    """E[S_H]=H*mu under stationary initialization."""

    H = int(horizon)
    if H <= 0:
        raise ValueError("horizon must be positive")
    return H * stationary_mean_selection(stationary, transition, rewards)


def expected_selection_activity(
    horizon: int,
    stationary: Sequence[float],
    transition: Sequence[Sequence[float]],
    rewards: Sequence[float],
) -> float:
    """Expected sum of absolute state-specific selection magnitudes."""

    H = int(horizon)
    if H <= 0:
        raise ValueError("horizon must be positive")
    return H * stationary_mean_absolute_selection(stationary, transition, rewards)


def cumulative_selection_variance(
    horizon: int,
    stationary: Sequence[float],
    transition: Sequence[Sequence[float]],
    rewards: Sequence[float],
) -> float:
    """Exact stationary finite-horizon variance of cumulative selection."""

    H = int(horizon)
    if H <= 0:
        raise ValueError("horizon must be positive")
    gamma = covariance_sequence(H - 1, stationary, transition, rewards)
    raw = H * gamma[0] + 2.0 * sum((H - k) * gamma[k] for k in range(1, H))
    if raw < 0.0 and abs(raw) < 1e-8:
        raw = 0.0
    if raw < 0.0:
        raise ArithmeticError("stationary covariance sum produced negative cumulative variance")
    return raw


def rms_cumulative_selection(
    horizon: int,
    stationary: Sequence[float],
    transition: Sequence[Sequence[float]],
    rewards: Sequence[float],
) -> float:
    """sqrt(E[S_H^2]) under stationary community switching."""

    mean = expected_cumulative_selection(horizon, stationary, transition, rewards)
    variance = cumulative_selection_variance(horizon, stationary, transition, rewards)
    return sqrt(max(0.0, mean * mean + variance))


def rms_retention_fraction(
    horizon: int,
    stationary: Sequence[float],
    transition: Sequence[Sequence[float]],
    rewards: Sequence[float],
) -> float:
    """RMS net selection divided by expected absolute selection activity."""

    activity = expected_selection_activity(horizon, stationary, transition, rewards)
    if activity <= _TOL:
        return 0.0
    return rms_cumulative_selection(horizon, stationary, transition, rewards) / activity


def asymptotic_directional_fraction(
    stationary: Sequence[float],
    transition: Sequence[Sequence[float]],
    rewards: Sequence[float],
) -> float:
    """Candidate long-run retained fraction |mean selection| / E|selection|.

    For an ergodic finite-state chain with summable reward autocovariance this is
    the limit of the RMS retention fraction.  This function returns the algebraic
    ratio and does not itself certify ergodicity or a spectral gap.
    """

    mean = abs(stationary_mean_selection(stationary, transition, rewards))
    activity = stationary_mean_absolute_selection(stationary, transition, rewards)
    if activity <= _TOL:
        return 0.0
    return mean / activity


def directional_signal_to_noise(
    horizon: int,
    stationary: Sequence[float],
    transition: Sequence[Sequence[float]],
    rewards: Sequence[float],
) -> float:
    """Absolute cumulative mean divided by finite-horizon standard deviation."""

    mean = abs(expected_cumulative_selection(horizon, stationary, transition, rewards))
    variance = cumulative_selection_variance(horizon, stationary, transition, rewards)
    if variance <= _TOL:
        return inf if mean > _TOL else 0.0
    return mean / sqrt(variance)


def structural_rewards_from_tasks(
    tasks: Sequence[FiniteTask],
    *,
    lambda_cost: float = 1.0,
    control_cost: float = 0.0,
) -> tuple[float, ...]:
    """Map finite community-state sensing tasks directly to Markov rewards."""

    if not tasks:
        raise ValueError("tasks must be non-empty")
    return tuple(
        structural_selection_state(
            task,
            lambda_cost=lambda_cost,
            control_cost=control_cost,
        ).log_fitness_ratio
        for task in tasks
    )


@dataclass(frozen=True)
class CommunityMarkovSelectionSummary:
    state_count: int
    stationary_mean_selection: float
    stationary_mean_absolute_selection: float
    asymptotic_directional_fraction: float
    horizon: int
    expected_cumulative_selection: float
    cumulative_variance: float
    rms_cumulative_selection: float
    rms_retention_fraction: float
    directional_signal_to_noise: float


def summarize_markov_selection(
    horizon: int,
    stationary: Sequence[float],
    transition: Sequence[Sequence[float]],
    rewards: Sequence[float],
) -> CommunityMarkovSelectionSummary:
    """Collect finite- and long-horizon quantities for community-state selection."""

    pi, P, s = _validate(stationary, transition, rewards)
    H = int(horizon)
    if H <= 0:
        raise ValueError("horizon must be positive")
    mean = sum(pi[i] * s[i] for i in range(len(pi)))
    abs_mean = sum(pi[i] * abs(s[i]) for i in range(len(pi)))
    cumulative_mean = H * mean
    variance = cumulative_selection_variance(H, pi, P, s)
    rms = sqrt(max(0.0, cumulative_mean * cumulative_mean + variance))
    activity = H * abs_mean
    return CommunityMarkovSelectionSummary(
        state_count=len(pi),
        stationary_mean_selection=mean,
        stationary_mean_absolute_selection=abs_mean,
        asymptotic_directional_fraction=(abs(mean) / abs_mean if abs_mean > _TOL else 0.0),
        horizon=H,
        expected_cumulative_selection=cumulative_mean,
        cumulative_variance=variance,
        rms_cumulative_selection=rms,
        rms_retention_fraction=(rms / activity if activity > _TOL else 0.0),
        directional_signal_to_noise=directional_signal_to_noise(H, pi, P, s),
    )
