"""Evolutionary timescale filters for fluctuating selection.

The core distinction is between short-term evolutionary *activity* and
long-term *retained change*.  Under a weak-selection scalar response

    delta z_t = G * beta_t,

large |beta_t| can generate rapid contemporary evolution even when sign
changes later cancel most of the cumulative displacement.

The stochastic formulas below are standard partial-sum covariance identities;
the repository-specific use is to make them the temporal compression layer for
selection generated by an upstream individual -> interaction -> community
feedback loop.
"""

from __future__ import annotations

from dataclasses import dataclass
from math import isclose, sqrt
from typing import Iterable, Sequence


_TOL = 1e-12


def _as_sequence(values: Iterable[float], *, name: str) -> tuple[float, ...]:
    out = tuple(float(x) for x in values)
    if not out:
        raise ValueError(f"{name} must be non-empty")
    return out


def evolutionary_activity(selection: Iterable[float], evolvability: float = 1.0) -> float:
    """Total absolute weak-selection response across the observation window."""

    beta = _as_sequence(selection, name="selection")
    G = float(evolvability)
    if G < 0:
        raise ValueError("evolvability must be non-negative")
    return G * sum(abs(x) for x in beta)


def cumulative_response(selection: Iterable[float], evolvability: float = 1.0) -> float:
    """Signed cumulative weak-selection response."""

    beta = _as_sequence(selection, name="selection")
    G = float(evolvability)
    if G < 0:
        raise ValueError("evolvability must be non-negative")
    return G * sum(beta)


def retained_change(selection: Iterable[float], evolvability: float = 1.0) -> float:
    """Absolute net evolutionary displacement retained at the end of a window."""

    return abs(cumulative_response(selection, evolvability=evolvability))


def retention_ratio(selection: Iterable[float], evolvability: float = 1.0) -> float:
    """Retained change divided by total evolutionary activity.

    The ratio lies in [0, 1].  A value of 1 means all non-zero selection
    responses point in the same direction; a value near 0 means strong
    short-term responses largely cancel over the chosen horizon.
    """

    beta = _as_sequence(selection, name="selection")
    activity = evolutionary_activity(beta, evolvability=evolvability)
    if isclose(activity, 0.0, abs_tol=_TOL, rel_tol=0.0):
        return 0.0
    return retained_change(beta, evolvability=evolvability) / activity


def partial_sum_variance(
    horizon: int,
    autocovariance: Sequence[float],
    evolvability: float = 1.0,
) -> float:
    """Exact variance of cumulative response from a stationary selection process.

    ``autocovariance[k]`` is gamma(k)=Cov(beta_t,beta_{t+k}).  At least
    ``horizon`` lags including k=0 must be supplied.
    """

    H = int(horizon)
    if H <= 0:
        raise ValueError("horizon must be positive")
    gamma = tuple(float(x) for x in autocovariance)
    if len(gamma) < H:
        raise ValueError("autocovariance must include lags 0..horizon-1")
    G = float(evolvability)
    if G < 0:
        raise ValueError("evolvability must be non-negative")
    raw = H * gamma[0] + 2.0 * sum((H - k) * gamma[k] for k in range(1, H))
    if raw < 0 and abs(raw) < 1e-10:
        raw = 0.0
    if raw < 0:
        raise ValueError("autocovariance sequence implies a negative partial-sum variance")
    return (G * G) * raw


def coherence_multiplier(horizon: int, autocorrelation: Sequence[float]) -> float:
    """Variance multiplier relative to temporally independent selection.

    For a stationary process with variance sigma^2,

        Var(sum beta_t) = H sigma^2 * coherence_multiplier.
    """

    H = int(horizon)
    if H <= 0:
        raise ValueError("horizon must be positive")
    rho = tuple(float(x) for x in autocorrelation)
    if len(rho) < H:
        raise ValueError("autorrelation must include lags 0..horizon-1")
    if not isclose(rho[0], 1.0, abs_tol=_TOL, rel_tol=0.0):
        raise ValueError("autocorrelation[0] must equal 1")
    return 1.0 + 2.0 * sum((1.0 - k / H) * rho[k] for k in range(1, H))


def ar1_partial_sum_factor(horizon: int, phi: float) -> float:
    """Return E[(sum X_t)^2] for unit-variance AR(1)-correlation phi^k.

    The same formula applies to a stationary symmetric two-state Markov sign
    process X_t in {-1,+1} with lag-one correlation ``phi``.
    """

    H = int(horizon)
    phi = float(phi)
    if H <= 0:
        raise ValueError("horizon must be positive")
    if phi < -1.0 or phi > 1.0:
        raise ValueError("phi must lie in [-1, 1]")
    if isclose(phi, 1.0, abs_tol=_TOL, rel_tol=0.0):
        return float(H * H)
    return float(
        (H * (1.0 - phi * phi) - 2.0 * phi + 2.0 * (phi ** (H + 1)))
        / ((1.0 - phi) ** 2)
    )


def ar1_coherence_multiplier(horizon: int, phi: float) -> float:
    """AR(1) selection-coherence multiplier relative to independence."""

    H = int(horizon)
    return ar1_partial_sum_factor(H, phi) / H


def ar1_rms_retained_change(
    horizon: int,
    selection_magnitude: float = 1.0,
    phi: float = 0.0,
    evolvability: float = 1.0,
) -> float:
    """RMS retained displacement for beta_t=s*X_t with Corr(X_t,X_t+k)=phi^k."""

    s = abs(float(selection_magnitude))
    G = float(evolvability)
    if G < 0:
        raise ValueError("evolvability must be non-negative")
    return G * s * sqrt(max(0.0, ar1_partial_sum_factor(horizon, phi)))


def ar1_rms_retention_ratio(horizon: int, phi: float) -> float:
    """RMS net displacement divided by H units of per-generation activity."""

    H = int(horizon)
    return sqrt(max(0.0, ar1_partial_sum_factor(H, phi))) / H


def asymptotic_ar1_coherence_multiplier(phi: float) -> float:
    """Long-horizon multiplier (1+phi)/(1-phi) for |phi|<1."""

    phi = float(phi)
    if not (-1.0 < phi < 1.0):
        raise ValueError("asymptotic multiplier requires -1 < phi < 1")
    return (1.0 + phi) / (1.0 - phi)


@dataclass(frozen=True)
class TimescaleSummary:
    horizon: int
    activity: float
    signed_response: float
    retained_change: float
    retention_ratio: float


def summarize_selection_path(
    selection: Iterable[float], evolvability: float = 1.0
) -> TimescaleSummary:
    beta = _as_sequence(selection, name="selection")
    return TimescaleSummary(
        horizon=len(beta),
        activity=evolutionary_activity(beta, evolvability=evolvability),
        signed_response=cumulative_response(beta, evolvability=evolvability),
        retained_change=retained_change(beta, evolvability=evolvability),
        retention_ratio=retention_ratio(beta, evolvability=evolvability),
    )
