"""Public entrypoint for extremal finite adaptive-gain constructions and bounds."""

from .binary_unit_cost_extremal_bounds import (
    BinaryUnitCostWorldQueryRatioReceipt,
    binary_tree_fixed_cost_bound,
    sharp_binary_unit_cost_ratio,
    sharp_binary_unit_cost_ratio_receipt,
    sharp_binary_unit_cost_ratio_witness,
    threshold_path_task,
)
from .extremal_routing import (
    ExtremalRoutingReceipt,
    RatioThreeHalvesMinimalityReceipt,
    depth_two_fixed_cost_world_bound,
    extremal_routing_receipt,
    k_branch_routing_task,
    ratio_above_three_halves_minimality,
)
from .extremal_routing_family import (
    BinaryExtremalRoutingFamilyReceipt,
    ExtremalRoutingFamilyReceipt,
    UnitCostRatioThresholdReceipt,
    binary_extremal_routing_family_audit,
    binary_extremal_routing_task,
    extremal_routing_family_audit,
    extremal_routing_task,
    first_unit_cost_ratio_above_three_halves_receipt,
    unit_cost_ratio_upper_bound_by_world_count,
)
from .unit_cost_extremal_bounds import (
    AdaptiveTreeUnionBoundReceipt,
    UnitCostWorldQueryRatioReceipt,
    adaptive_tree_union_bound_receipt,
    maximum_productive_tree_internal_nodes,
    sharp_unit_cost_ratio,
    sharp_unit_cost_ratio_receipt,
    sharp_unit_cost_ratio_witness,
    unit_cost_fixed_cost_bound,
)

__all__ = [
    "BinaryUnitCostWorldQueryRatioReceipt",
    "binary_tree_fixed_cost_bound",
    "sharp_binary_unit_cost_ratio",
    "sharp_binary_unit_cost_ratio_receipt",
    "sharp_binary_unit_cost_ratio_witness",
    "threshold_path_task",
    "ExtremalRoutingReceipt",
    "RatioThreeHalvesMinimalityReceipt",
    "depth_two_fixed_cost_world_bound",
    "extremal_routing_receipt",
    "k_branch_routing_task",
    "ratio_above_three_halves_minimality",
    "BinaryExtremalRoutingFamilyReceipt",
    "ExtremalRoutingFamilyReceipt",
    "UnitCostRatioThresholdReceipt",
    "binary_extremal_routing_family_audit",
    "binary_extremal_routing_task",
    "extremal_routing_family_audit",
    "extremal_routing_task",
    "first_unit_cost_ratio_above_three_halves_receipt",
    "unit_cost_ratio_upper_bound_by_world_count",
    "AdaptiveTreeUnionBoundReceipt",
    "UnitCostWorldQueryRatioReceipt",
    "adaptive_tree_union_bound_receipt",
    "maximum_productive_tree_internal_nodes",
    "sharp_unit_cost_ratio",
    "sharp_unit_cost_ratio_receipt",
    "sharp_unit_cost_ratio_witness",
    "unit_cost_fixed_cost_bound",
]
