"""Necessary architecture bounds under nonlinear sensing-to-selection lifts.

The original reachability result uses a linear structural lift

    G = a * Delta_g,

where ``Delta_g`` is the integer adaptive/fixed structural gap.  This module
keeps the biological conclusion when that equality is relaxed.

Assume instead that selection is generated by a nondecreasing function
``f(g)`` whose marginal change is bounded above by ``L`` on the relevant
structural-gap domain.  If local feedback converts a selection contrast into
loop gain with positive scale ``B = -beta*e``, then

    0 <= Delta_s <= L * Delta_g
    0 <= G <= B * L * Delta_g.

Therefore a local regime requiring the strict threshold ``G > G_osc`` can be
reached only if

    Delta_g > G_osc / (B*L).

For integer structural gaps this gives an exact necessary lower bound.  Any
architecture class whose maximum possible gap is below that bound cannot
produce the requested oscillatory regime for *any* lift in the declared
monotone-Lipschitz class.

This is a no-go/necessary-condition theorem.  Crossing the bound does not by
itself prove reachability because a particular nonlinear lift may realize less
than its allowed Lipschitz ceiling.  The linear model is recovered as the
special case ``f(g)=lambda*g`` with ``B*L=a``.
"""

from __future__ import annotations

from dataclasses import dataclass
from math import floor, inf, isfinite, nextafter

from .general_evolutionary_response import general_response_thresholds
from .structural_oscillation_reachability import (
    bounded_arity_gap_ceiling_over_adaptive_depth,
)


def _positive_finite(value: float, name: str) -> float:
    out = float(value)
    if not isfinite(out) or out <= 0.0:
        raise ValueError(f"{name} must be finite and positive")
    return out


def maximum_feedback_gain_under_lipschitz_lift(
    structural_gap: int,
    *,
    feedback_per_selection: float,
    max_selection_gain_per_gap: float,
) -> float:
    """Upper bound ``B*L*Delta_g`` for a monotone L-Lipschitz lift.

    ``structural_gap`` is the integer difference ``C_F-C_A``.  The function
    returns a ceiling, not an asserted realized feedback gain.
    """

    if type(structural_gap) is not int or structural_gap < 0:
        raise ValueError("structural_gap must be a nonnegative integer")
    b = _positive_finite(feedback_per_selection, "feedback_per_selection")
    L = _positive_finite(
        max_selection_gain_per_gap,
        "max_selection_gain_per_gap",
    )
    return b * L * structural_gap


def minimum_integer_gap_for_oscillation_under_lipschitz_lift(
    *,
    evolutionary_persistence: float,
    community_memory: float,
    feedback_per_selection: float,
    max_selection_gain_per_gap: float,
) -> int:
    """Necessary integer gap for crossing the complex-eigenpair threshold.

    If ``f`` is nondecreasing and L-Lipschitz and ``G=B*Delta_s``, then
    ``G <= B*L*Delta_g``.  Because oscillation requires the strict inequality
    ``G > G_osc``, a necessary condition is

        Delta_g > G_osc / (B*L).

    The returned integer is therefore ``floor(G_osc/(B*L)) + 1``, with the
    strict boundary protected numerically by ``nextafter``.
    """

    b = _positive_finite(feedback_per_selection, "feedback_per_selection")
    L = _positive_finite(
        max_selection_gain_per_gap,
        "max_selection_gain_per_gap",
    )
    threshold = general_response_thresholds(
        evolutionary_persistence,
        community_memory,
    ).oscillation_gain
    ratio = threshold / (b * L)
    return floor(nextafter(ratio, inf)) + 1


def oscillation_is_ruled_out_under_lipschitz_lift(
    structural_gap_ceiling: int,
    *,
    evolutionary_persistence: float,
    community_memory: float,
    feedback_per_selection: float,
    max_selection_gain_per_gap: float,
) -> bool:
    """Whether an architecture class is too simple to reach oscillation.

    Returns ``True`` exactly when even the largest feedback allowed by the
    Lipschitz ceiling at ``structural_gap_ceiling`` fails to exceed ``G_osc``.
    A ``False`` result means only "not ruled out by this theorem"; it is not a
    sufficiency claim.
    """

    max_gain = maximum_feedback_gain_under_lipschitz_lift(
        structural_gap_ceiling,
        feedback_per_selection=feedback_per_selection,
        max_selection_gain_per_gap=max_selection_gain_per_gap,
    )
    threshold = general_response_thresholds(
        evolutionary_persistence,
        community_memory,
    ).oscillation_gain
    return max_gain <= threshold


@dataclass(frozen=True)
class LipschitzOscillationNoGoReceipt:
    evolutionary_persistence: float
    community_memory: float
    feedback_per_selection: float
    max_selection_gain_per_gap: float
    effective_gain_ceiling_per_gap: float
    oscillation_gain: float
    necessary_integer_gap: int
    binary_five_world_gap_ceiling: int
    binary_four_query_gap_ceiling: int
    binary_four_frontier_edge_gap_ceiling: int
    five_world_scope_ruled_out: bool
    four_query_scope_ruled_out: bool
    four_frontier_edge_scope_ruled_out: bool
    linear_special_case_matches_existing_a: bool
    theorem_holds: bool
    scope: str = "nonlinear_monotone_lipschitz_oscillation_no_go"


def canonical_binary_lipschitz_no_go_receipt() -> LipschitzOscillationNoGoReceipt:
    """Canonical no-go matching the existing ``a=1/8`` linear example.

    We factor ``a`` into a feedback-per-selection scale ``B=1/2`` and a maximum
    marginal sensing-to-selection gain ``L=1/4``.  Their product is ``1/8``.
    The nonlinear theorem then proves that every monotone lift with slope at
    most ``1/4`` still requires structural gap at least two.  Existing binary
    extremal bounds cap all tasks with <=5 worlds, <=4 queries, or <=4 minimal
    productive-frontier obligations at gap one, so all three smaller scopes are
    ruled out without assuming a linear lift.
    """

    alpha = 1.0
    phi = 0.5
    feedback_scale = 0.5
    max_marginal_gain = 0.25
    effective = feedback_scale * max_marginal_gain
    thresholds = general_response_thresholds(alpha, phi)

    required_gap = minimum_integer_gap_for_oscillation_under_lipschitz_lift(
        evolutionary_persistence=alpha,
        community_memory=phi,
        feedback_per_selection=feedback_scale,
        max_selection_gain_per_gap=max_marginal_gain,
    )

    five_world_gap = bounded_arity_gap_ceiling_over_adaptive_depth(5, 20, 2)
    four_query_gap = bounded_arity_gap_ceiling_over_adaptive_depth(16, 4, 2)
    four_frontier_gap = bounded_arity_gap_ceiling_over_adaptive_depth(
        16,
        16,
        2,
        frontier_edge_cap=4,
    )

    five_world_no_go = oscillation_is_ruled_out_under_lipschitz_lift(
        five_world_gap,
        evolutionary_persistence=alpha,
        community_memory=phi,
        feedback_per_selection=feedback_scale,
        max_selection_gain_per_gap=max_marginal_gain,
    )
    four_query_no_go = oscillation_is_ruled_out_under_lipschitz_lift(
        four_query_gap,
        evolutionary_persistence=alpha,
        community_memory=phi,
        feedback_per_selection=feedback_scale,
        max_selection_gain_per_gap=max_marginal_gain,
    )
    four_frontier_no_go = oscillation_is_ruled_out_under_lipschitz_lift(
        four_frontier_gap,
        evolutionary_persistence=alpha,
        community_memory=phi,
        feedback_per_selection=feedback_scale,
        max_selection_gain_per_gap=max_marginal_gain,
    )

    theorem_holds = (
        thresholds.oscillation_gain == 0.125
        and effective == 0.125
        and required_gap == 2
        and five_world_gap == 1
        and four_query_gap == 1
        and four_frontier_gap == 1
        and five_world_no_go
        and four_query_no_go
        and four_frontier_no_go
    )
    if not theorem_holds:
        raise ArithmeticError("canonical nonlinear oscillation no-go failed")

    return LipschitzOscillationNoGoReceipt(
        evolutionary_persistence=alpha,
        community_memory=phi,
        feedback_per_selection=feedback_scale,
        max_selection_gain_per_gap=max_marginal_gain,
        effective_gain_ceiling_per_gap=effective,
        oscillation_gain=thresholds.oscillation_gain,
        necessary_integer_gap=required_gap,
        binary_five_world_gap_ceiling=five_world_gap,
        binary_four_query_gap_ceiling=four_query_gap,
        binary_four_frontier_edge_gap_ceiling=four_frontier_gap,
        five_world_scope_ruled_out=five_world_no_go,
        four_query_scope_ruled_out=four_query_no_go,
        four_frontier_edge_scope_ruled_out=four_frontier_no_go,
        linear_special_case_matches_existing_a=(effective == 0.125),
        theorem_holds=theorem_holds,
    )
