"""Necessary architecture bounds under nonlinear sensing-to-selection lifts.

Each ecological state ``i`` has its own adaptive-versus-fixed sensing gap

    g_i = C_F(i) - C_A(i) >= 0.

Eco-evolutionary feedback is driven by a contrast between ecological states,
not by one state gap in isolation.  For an ordered pair with ``g_high>=g_low``
define

    Delta_g = g_high - g_low >= 0.

Assume selection is generated by a nondecreasing function ``f(g)`` whose
marginal change is bounded above by ``L`` on the relevant state-gap domain.  If
local feedback converts a selection contrast into loop gain with positive scale
``B=-beta*e``, then

    0 <= Delta_s <= L * Delta_g
    0 <= G <= B * L * Delta_g.

Therefore a local regime requiring the strict threshold ``G>G_osc`` can be
reached only if

    Delta_g > G_osc / (B*L).

For integer state gaps, this gives an exact necessary lower bound on the
between-state structural contrast.  If an architecture class bounds every
state gap by ``0<=g_i<=q_max``, then it also bounds every ordered contrast by
``Delta_g<=q_max``.  Hence ``B*L*q_max<=G_osc`` is a class-level no-go.

This is a necessary-condition theorem only.  Crossing the bound does not prove
reachability because a particular nonlinear lift may realize less than its
allowed Lipschitz ceiling.  The additive linear model is recovered as the
special case ``f(g)=lambda*g`` with ``B*L=a``.
"""

from __future__ import annotations

from dataclasses import dataclass
from math import floor, inf, isfinite, nextafter

from .general_evolutionary_response import general_response_thresholds
from .structural_oscillation_reachability import (
    bounded_arity_gap_ceiling_over_adaptive_depth,
)


def _positive_finite(value: float, name: str) -> float:
    out = float(value)
    if not isfinite(out) or out <= 0.0:
        raise ValueError(f"{name} must be finite and positive")
    return out


def maximum_feedback_gain_under_lipschitz_lift(
    structural_gap_contrast: int,
    *,
    feedback_per_selection: float,
    max_selection_gain_per_gap: float,
) -> float:
    """Upper bound ``B*L*Delta_g`` for an ordered between-state contrast.

    ``structural_gap_contrast`` is ``g_high-g_low`` where each state-specific
    ``g_i=C_F(i)-C_A(i)`` is a nonnegative integer.  The return value is a
    ceiling, not an asserted realized feedback gain.
    """

    if type(structural_gap_contrast) is not int or structural_gap_contrast < 0:
        raise ValueError("structural_gap_contrast must be a nonnegative integer")
    b = _positive_finite(feedback_per_selection, "feedback_per_selection")
    L = _positive_finite(
        max_selection_gain_per_gap,
        "max_selection_gain_per_gap",
    )
    return b * L * structural_gap_contrast


def minimum_integer_gap_contrast_for_oscillation_under_lipschitz_lift(
    *,
    evolutionary_persistence: float,
    community_memory: float,
    feedback_per_selection: float,
    max_selection_gain_per_gap: float,
) -> int:
    """Necessary integer between-state gap contrast for oscillatory return.

    Because ``G<=B*L*Delta_g`` and oscillation requires ``G>G_osc``, a
    necessary condition is ``Delta_g>G_osc/(B*L)``.
    """

    b = _positive_finite(feedback_per_selection, "feedback_per_selection")
    L = _positive_finite(
        max_selection_gain_per_gap,
        "max_selection_gain_per_gap",
    )
    threshold = general_response_thresholds(
        evolutionary_persistence,
        community_memory,
    ).oscillation_gain
    ratio = threshold / (b * L)
    return floor(nextafter(ratio, inf)) + 1


def minimum_integer_gap_for_oscillation_under_lipschitz_lift(**kwargs) -> int:
    """Backward-compatible alias; the returned gap is a state-to-state contrast."""

    return minimum_integer_gap_contrast_for_oscillation_under_lipschitz_lift(
        **kwargs
    )


def oscillation_is_ruled_out_under_lipschitz_lift(
    structural_gap_contrast_ceiling: int,
    *,
    evolutionary_persistence: float,
    community_memory: float,
    feedback_per_selection: float,
    max_selection_gain_per_gap: float,
) -> bool:
    """Whether a contrast ceiling is too small to reach oscillatory return.

    ``True`` means even the largest feedback allowed at the declared
    between-state contrast ceiling fails to exceed ``G_osc``.  ``False`` means
    only "not ruled out by this theorem"; it is not a sufficiency claim.
    """

    max_gain = maximum_feedback_gain_under_lipschitz_lift(
        structural_gap_contrast_ceiling,
        feedback_per_selection=feedback_per_selection,
        max_selection_gain_per_gap=max_selection_gain_per_gap,
    )
    threshold = general_response_thresholds(
        evolutionary_persistence,
        community_memory,
    ).oscillation_gain
    return max_gain <= threshold


@dataclass(frozen=True)
class LipschitzOscillationNoGoReceipt:
    evolutionary_persistence: float
    community_memory: float
    feedback_per_selection: float
    max_selection_gain_per_gap: float
    effective_gain_ceiling_per_gap_contrast: float
    oscillation_gain: float
    necessary_integer_gap_contrast: int
    binary_five_world_state_gap_ceiling: int
    binary_four_query_state_gap_ceiling: int
    binary_four_frontier_edge_state_gap_ceiling: int
    binary_five_world_contrast_ceiling: int
    binary_four_query_contrast_ceiling: int
    binary_four_frontier_edge_contrast_ceiling: int
    five_world_scope_ruled_out: bool
    four_query_scope_ruled_out: bool
    four_frontier_edge_scope_ruled_out: bool
    constructive_low_state_gap: int
    constructive_high_state_gap: int
    linear_special_case_matches_existing_a: bool
    theorem_holds: bool
    scope: str = "nonlinear_monotone_lipschitz_between_state_oscillation_no_go"


def canonical_binary_lipschitz_no_go_receipt() -> LipschitzOscillationNoGoReceipt:
    """Canonical two-state no-go matching the existing ``a=1/8`` example.

    ``B=1/2`` and ``L=1/4`` give ``B*L=1/8``.  The oscillation threshold then
    requires a between-state structural contrast of at least two.  Existing
    binary extremal bounds cap every state-specific task with <=5 worlds,
    <=4 queries, or <=4 minimal productive-frontier obligations at ``g_i<=1``.
    Because state gaps are nonnegative, any two states drawn from one such class
    satisfy ``|Delta_g|<=1`` and oscillation is ruled out for the whole class.

    The constructive linear special case pairs a zero-gap state with the known
    six-world/five-query gap-two state, yielding contrast two.  The nonlinear
    theorem itself does not claim that every admissible lift realizes that gain.
    """

    alpha = 1.0
    phi = 0.5
    feedback_scale = 0.5
    max_marginal_gain = 0.25
    effective = feedback_scale * max_marginal_gain
    thresholds = general_response_thresholds(alpha, phi)

    required_contrast = (
        minimum_integer_gap_contrast_for_oscillation_under_lipschitz_lift(
            evolutionary_persistence=alpha,
            community_memory=phi,
            feedback_per_selection=feedback_scale,
            max_selection_gain_per_gap=max_marginal_gain,
        )
    )

    five_world_state_gap = bounded_arity_gap_ceiling_over_adaptive_depth(5, 20, 2)
    four_query_state_gap = bounded_arity_gap_ceiling_over_adaptive_depth(16, 4, 2)
    four_frontier_state_gap = bounded_arity_gap_ceiling_over_adaptive_depth(
        16,
        16,
        2,
        frontier_edge_cap=4,
    )

    # Because all state-specific gaps are >=0 and <= the class ceiling, the
    # largest possible ordered contrast between any two states is the same
    # numerical ceiling.
    five_world_contrast = five_world_state_gap
    four_query_contrast = four_query_state_gap
    four_frontier_contrast = four_frontier_state_gap

    five_world_no_go = oscillation_is_ruled_out_under_lipschitz_lift(
        five_world_contrast,
        evolutionary_persistence=alpha,
        community_memory=phi,
        feedback_per_selection=feedback_scale,
        max_selection_gain_per_gap=max_marginal_gain,
    )
    four_query_no_go = oscillation_is_ruled_out_under_lipschitz_lift(
        four_query_contrast,
        evolutionary_persistence=alpha,
        community_memory=phi,
        feedback_per_selection=feedback_scale,
        max_selection_gain_per_gap=max_marginal_gain,
    )
    four_frontier_no_go = oscillation_is_ruled_out_under_lipschitz_lift(
        four_frontier_contrast,
        evolutionary_persistence=alpha,
        community_memory=phi,
        feedback_per_selection=feedback_scale,
        max_selection_gain_per_gap=max_marginal_gain,
    )

    low_gap = 0
    high_gap = 2
    theorem_holds = (
        thresholds.oscillation_gain == 0.125
        and effective == 0.125
        and required_contrast == 2
        and five_world_state_gap == 1
        and four_query_state_gap == 1
        and four_frontier_state_gap == 1
        and five_world_contrast == 1
        and four_query_contrast == 1
        and four_frontier_contrast == 1
        and high_gap - low_gap == required_contrast
        and five_world_no_go
        and four_query_no_go
        and four_frontier_no_go
    )
    if not theorem_holds:
        raise ArithmeticError("canonical nonlinear between-state oscillation no-go failed")

    return LipschitzOscillationNoGoReceipt(
        evolutionary_persistence=alpha,
        community_memory=phi,
        feedback_per_selection=feedback_scale,
        max_selection_gain_per_gap=max_marginal_gain,
        effective_gain_ceiling_per_gap_contrast=effective,
        oscillation_gain=thresholds.oscillation_gain,
        necessary_integer_gap_contrast=required_contrast,
        binary_five_world_state_gap_ceiling=five_world_state_gap,
        binary_four_query_state_gap_ceiling=four_query_state_gap,
        binary_four_frontier_edge_state_gap_ceiling=four_frontier_state_gap,
        binary_five_world_contrast_ceiling=five_world_contrast,
        binary_four_query_contrast_ceiling=four_query_contrast,
        binary_four_frontier_edge_contrast_ceiling=four_frontier_contrast,
        five_world_scope_ruled_out=five_world_no_go,
        four_query_scope_ruled_out=four_query_no_go,
        four_frontier_edge_scope_ruled_out=four_frontier_no_go,
        constructive_low_state_gap=low_gap,
        constructive_high_state_gap=high_gap,
        linear_special_case_matches_existing_a=(effective == 0.125),
        theorem_holds=theorem_holds,
    )
